### ISSUE TITLE
TODO List 

### ISSUE THREAD

**Issue by muzikr** [muzikr/Shapleypy#1]
This is what still remains to implement:
# Input 
- [ ] Getting a game
  - [ ] Game generators
    - [ ] Class generators
    - [ ] Domain
  - [ ] Loading game from file
  - [ ] Getting it from user (array)
  - User do not have to give all the values

# Output
- [ ] Saving game into file

# Computation
- [ ] Check into which class given game belongs
- [ ] Solution concepts
  - [ ] Shapley value
  - [ ] Banzhof value
  - [ ] Weber's set
  - [ ] Nucleus 
  - [ ] Core
- [ ] Integer solutions
